apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zoomdata-postgres
  name: zoomdata-postgres
spec:
  replicas: 1
  selector:
    io.kompose.service: zoomdata-postgres
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zoomdata-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          image: ' '
          name: zoomdata-postgres
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: zoomdata-postgres-claim0
            - mountPath: /docker-entrypoint-initdb.d
              name: zoomdata-postgres-claim1
      hostname: zoomdata-postgres
      restartPolicy: Always
      volumes:
        - name: zoomdata-postgres-claim0
          persistentVolumeClaim:
            claimName: zoomdata-postgres-claim0
        - name: zoomdata-postgres-claim1
          persistentVolumeClaim:
            claimName: zoomdata-postgres-claim1
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - zoomdata-postgres
        from:
          kind: ImageStreamTag
          name: zoomdata-postgres:9.5
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
