apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zoomdata-web
  name: zoomdata-web
spec:
  replicas: 1
  selector:
    io.kompose.service: zoomdata-web
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zoomdata-web
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - env:
            - name: DISCOVERY_REGISTRY_HOST
              value: zoomdata-consul
          image: ' '
          name: zoomdata-web
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /etc/zoomdata
              name: zoomdata-web-claim0
            - mountPath: /opt/zoomdata/logs
              name: zoomdata-web-claim1
      hostname: zoomdata-web
      restartPolicy: Always
      volumes:
        - name: zoomdata-web-claim0
          persistentVolumeClaim:
            claimName: zoomdata-web-claim0
        - name: zoomdata-web-claim1
          persistentVolumeClaim:
            claimName: zoomdata-web-claim1
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - zoomdata-web
        from:
          kind: ImageStreamTag
          name: 'zoomdata-web:'
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
