apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zoomdata-query-engine
  name: zoomdata-query-engine
spec:
  ports:
    - name: "5580"
      port: 5580
      targetPort: 5580
    - name: "4040"
      port: 4040
      targetPort: 4040
  selector:
    io.kompose.service: zoomdata-query-engine
status:
  loadBalancer: {}
