apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zoomdata-query-engine
  name: zoomdata-query-engine
spec:
  replicas: 1
  selector:
    io.kompose.service: zoomdata-query-engine
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zoomdata-query-engine
    spec:
      containers:
        - env:
            - name: DISCOVERY_REGISTRY_HOST
              value: zoomdata-consul
          image: ' '
          name: zoomdata-query-engine
          ports:
            - containerPort: 5580
            - containerPort: 4040
          resources: {}
          volumeMounts:
            - mountPath: /etc/zoomdata
              name: zoomdata-query-engine-claim0
            - mountPath: /opt/zoomdata/logs
              name: zoomdata-query-engine-claim1
      hostname: zoomdata-query-engine
      restartPolicy: Always
      volumes:
        - name: zoomdata-query-engine-claim0
          persistentVolumeClaim:
            claimName: zoomdata-query-engine-claim0
        - name: zoomdata-query-engine-claim1
          persistentVolumeClaim:
            claimName: zoomdata-query-engine-claim1
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - zoomdata-query-engine
        from:
          kind: ImageStreamTag
          name: 'zoomdata-query-engine:'
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
